USE [Kama.Bonyad.Organization]
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE [object_id] = OBJECT_ID('org.spDeleteClient'))
	DROP PROCEDURE org.spDeleteClient
GO

CREATE PROCEDURE org.spDeleteClient
	@AID UNIQUEIDENTIFIER,
	@ACurrentUserID UNIQUEIDENTIFIER,
	@ALog NVARCHAR(MAX)
WITH ENCRYPTION
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	DECLARE  
		@ID UNIQUEIDENTIFIER = @AID,
		@CurrentUserID UNIQUEIDENTIFIER = @ACurrentUserID,
		@Log NVARCHAR(MAX) = LTRIM(RTRIM(@ALog)),
		@Node HIERARCHYID 

	BEGIN TRY
		BEGIN TRAN
			DELETE FROM org.Client
			WHERE [ID] = @ID

			EXEC pbl.spAddLog @Log
		COMMIT
	END TRY
	BEGIN CATCH
		;THROW
	END CATCH

	RETURN @@ROWCOUNT
END