USE [Kama.Sm.Organization]
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE [object_id] = OBJECT_ID('org.spDeletePlace'))
DROP PROCEDURE org.spDeletePlace
GO

CREATE PROCEDURE org.spDeletePlace
	@AID UNIQUEIDENTIFIER,
	@ALog NVARCHAR(MAX)

WITH ENCRYPTION
AS
BEGIN

	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	DECLARE
		  @ID UNIQUEIDENTIFIER = @AID
		, @Log NVARCHAR(MAX) = LTRIM(RTRIM(@ALog))
		, @Node HIERARCHYID 

	SET @Node = (SELECT [Node] FROM org.Place WHERE ID = @ID)  

	BEGIN TRY
		BEGIN TRAN

			DELETE FROM org.Place
			WHERE [Node].IsDescendantOf(@Node) = 1

			EXEC pbl.spAddLog @Log
		COMMIT
	END TRY
	BEGIN CATCH
		;THROW
	END CATCH

	RETURN @@ROWCOUNT
END
